// Code goes here

(function() {
  'use strict';

  angular.module('myNewApp', []); //creating

  angular.module('myNewApp').controller('ParentController', ParentController);


  function ParentController() {
    var pc = this;
    this.name = 'angularjs new name';

    //get a lot of data via ajax
    this.users = [
      {
        "id":1,
        "gender":"male",
        "title":"Mr.",
        "firstName":"Ernesto",
        "middleInitial":"J",
        "surname":"Theroux",
        "streetAddress":"3426 Christie Way",
        "city":"Bedford",
        "state":"MA",
        "zipCode":"1730",
        "country":"United States",
        "email":"ErnestoJTheroux@dayrep.com",
        "username":"Himeacerhe",
        "birthday":"1/15/1968",
        "occupation":"Stevedore",
        "company":"Briazz",
        "latitude":"42.418043",
        "longitude":"-71.346313",
        "motto":"640K ought to be enough for anybody. (Bill Gates, 1981)",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":2,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Tammie",
        "middleInitial":"D",
        "surname":"Kitchens",
        "streetAddress":"4763 Passaic Street",
        "city":"Washington",
        "state":"DC",
        "zipCode":"20036",
        "country":"United States",
        "email":"TammieDKitchens@fleckens.hu",
        "username":"Allichere",
        "birthday":"8/6/1954",
        "occupation":"Tax assessor",
        "company":"La Petite Boulangerie",
        "latitude":"38.869451",
        "longitude":"-77.029803",
        "motto":"A newspaper is a collection of half-injustices",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":3,
        "gender":"male",
        "title":"Mr.",
        "firstName":"Douglas",
        "middleInitial":"C",
        "surname":"Secrist",
        "streetAddress":"3601 Little Street",
        "city":"Akron",
        "state":"OH",
        "zipCode":"44311",
        "country":"United States",
        "email":"DouglasCSecrist@fleckens.hu",
        "username":"Domence",
        "birthday":"10/25/1989",
        "occupation":"Diagnostic medical sonographer",
        "company":"First Rate Choice",
        "latitude":"41.069696",
        "longitude":"-81.505841",
        "motto":"All my hidden skills are undiscovered. - Clinton",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":4,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Lydia",
        "middleInitial":"C",
        "surname":"Lee",
        "streetAddress":"1015 Irish Lane",
        "city":"Monroe",
        "state":"WI",
        "zipCode":"53566",
        "country":"United States",
        "email":"LydiaCLee@gustr.com",
        "username":"Theeng1946",
        "birthday":"8/19/1946",
        "occupation":"Financial economist",
        "company":"Reliable Guidance",
        "latitude":"42.537259",
        "longitude":"-89.610218",
        "motto":"Are your cookies made with real Girl Scouts?",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":5,
        "gender":"female",
        "title":"Ms.",
        "firstName":"Kirstin",
        "middleInitial":"L",
        "surname":"Miller",
        "streetAddress":"3528 Waldeck Street",
        "city":"Dallas",
        "state":"TX",
        "zipCode":"75247",
        "country":"United States",
        "email":"KirstinLMiller@teleworm.us",
        "username":"Mity1974",
        "birthday":"11/3/1974",
        "occupation":"Power dispatcher",
        "company":"Woolf Brothers",
        "latitude":"32.815473",
        "longitude":"-96.897678",
        "motto":"But honey, we need a 2 gig drive for word processing!",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":6,
        "gender":"male",
        "title":"Mr.",
        "firstName":"David",
        "middleInitial":"V",
        "surname":"Burlison",
        "streetAddress":"2279 Matthews Street",
        "city":"Sterling",
        "state":"IL",
        "zipCode":"61081",
        "country":"United States",
        "email":"DavidVBurlison@armyspy.com",
        "username":"Perclovery",
        "birthday":"5/8/1992",
        "occupation":"Radio operator",
        "company":"William Wanamaker & Sons",
        "latitude":"41.745624",
        "longitude":"-89.802821",
        "motto":"DOS=HIGH Hmm, I knew it was on something...",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":7,
        "gender":"male",
        "title":"Mr.",
        "firstName":"Vance",
        "middleInitial":"R",
        "surname":"Warren",
        "streetAddress":"663 Clinton Street",
        "city":"Searcy",
        "state":"AR",
        "zipCode":"72143",
        "country":"United States",
        "email":"VanceRWarren@rhyta.com",
        "username":"Miseen1970",
        "birthday":"12/17/1970",
        "occupation":"Engineering manager",
        "company":"Mr Fables",
        "latitude":"35.174471",
        "longitude":"-91.739357",
        "motto":"Good morning! is an opinion, not a greeting.",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":8,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Deborah",
        "middleInitial":"C",
        "surname":"Coburn",
        "streetAddress":"3500 Echo Lane",
        "city":"Grand Rapids",
        "state":"MI",
        "zipCode":"49503",
        "country":"United States",
        "email":"DeborahCCoburn@jourrapide.com",
        "username":"Betheareast",
        "birthday":"4/22/1962",
        "occupation":"Finance officer",
        "company":"Veramons",
        "latitude":"42.999021",
        "longitude":"-85.576485",
        "motto":"Graphic Artist seeks Boss with vision impairment.",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":9,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Gladys",
        "middleInitial":"M",
        "surname":"Warnock",
        "streetAddress":"2498 Dola Mine Road",
        "city":"Durham",
        "state":"NC",
        "zipCode":"27707",
        "country":"United States",
        "email":"GladysMWarnock@cuvox.de",
        "username":"Magning1945",
        "birthday":"6/30/1945",
        "occupation":"Engineer",
        "company":"Newmark & Lewis",
        "latitude":"36.003132",
        "longitude":"-78.873303",
        "motto":"Ground Beef -- A Cow With No Legs!",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":10,
        "gender":"male",
        "title":"Mr.",
        "firstName":"David",
        "middleInitial":"R",
        "surname":"Thompson",
        "streetAddress":"231 Jefferson Street",
        "city":"Virginia Beach",
        "state":"VA",
        "zipCode":"23455",
        "country":"United States",
        "email":"DavidRThompson@cuvox.de",
        "username":"Snate1936",
        "birthday":"3/20/1936",
        "occupation":"Electronic home entertainment equipment repairer",
        "company":"Monk House Sales",
        "latitude":"36.813435",
        "longitude":"-76.152001",
        "motto":"Hex Dump - Where Witches put used curses?",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":11,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Maria",
        "middleInitial":"C",
        "surname":"Myers",
        "streetAddress":"1680 Dovetail Estates",
        "city":"Tupelo",
        "state":"OK",
        "zipCode":"74572",
        "country":"United States",
        "email":"MariaCMyers@rhyta.com",
        "username":"Frated85",
        "birthday":"2/25/1985",
        "occupation":"Radiation therapist",
        "company":"Gemco",
        "latitude":"34.673143",
        "longitude":"-96.452543",
        "motto":"I'd like all your $20 bills in this bag, \"To go\".",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":12,
        "gender":"female",
        "title":"Ms.",
        "firstName":"Diana",
        "middleInitial":"A",
        "surname":"Garza",
        "streetAddress":"505 Conifer Drive",
        "city":"Seattle",
        "state":"WA",
        "zipCode":"98122",
        "country":"United States",
        "email":"DianaAGarza@cuvox.de",
        "username":"Terew1978",
        "birthday":"5/18/1978",
        "occupation":"Account clerk",
        "company":"Standard Food",
        "latitude":"47.57336",
        "longitude":"-122.35858",
        "motto":"Leave my blouse alone! I said Spellcheck, not Spillcheck",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":13,
        "gender":"male",
        "title":"Mr.",
        "firstName":"Philip",
        "middleInitial":"J",
        "surname":"Vaughn",
        "streetAddress":"172 Quilly Lane",
        "city":"Columbus",
        "state":"OH",
        "zipCode":"43219",
        "country":"United States",
        "email":"PhilipJVaughn@jourrapide.com",
        "username":"Inne1984",
        "birthday":"3/17/1984",
        "occupation":"Professor",
        "company":"Electric Avenue",
        "latitude":"40.035256",
        "longitude":"-82.862775",
        "motto":"MEOW...SPLAT...\"RUFF\"...SPLAT...(Raining cats & dogs)",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":14,
        "gender":"female",
        "title":"Ms.",
        "firstName":"Helene",
        "middleInitial":"T",
        "surname":"Benjamin",
        "streetAddress":"1321 Stone Lane",
        "city":"West Chester",
        "state":"PA",
        "zipCode":"19382",
        "country":"United States",
        "email":"HeleneTBenjamin@fleckens.hu",
        "username":"Betied",
        "birthday":"11/13/1978",
        "occupation":"Occupational health nurse",
        "company":"Just For Fun",
        "latitude":"39.917502",
        "longitude":"-75.618456",
        "motto":"Please return stewardess to original upright position",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":15,
        "gender":"female",
        "title":"Mrs.",
        "firstName":"Sarah",
        "middleInitial":"C",
        "surname":"Newman",
        "streetAddress":"149 Burnside Avenue",
        "city":"Saint George",
        "state":"UT",
        "zipCode":"84770",
        "country":"United States",
        "email":"SarahCNewman@gustr.com",
        "username":"Thignot",
        "birthday":"3/19/1957",
        "occupation":"Employee benefits specialist",
        "company":"Kelly and Cohen",
        "latitude":"37.231806",
        "longitude":"-113.673907",
        "motto":"Sometimes a cigar is just a cigar - Freud",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":16,
        "gender":"female",
        "title":"Ms.",
        "firstName":"Pauline",
        "middleInitial":"A",
        "surname":"Hurst",
        "streetAddress":"2654 Hamill Avenue",
        "city":"La Mesa",
        "state":"CA",
        "zipCode":"91941",
        "country":"United States",
        "email":"PaulineAHurst@teleworm.us",
        "username":"Fation",
        "birthday":"1/11/1982",
        "occupation":"Electrician",
        "company":"Elm Farm",
        "latitude":"32.737361",
        "longitude":"-116.925017",
        "motto":"Uh honey, a P5 with a 20 monitor is perfect for mail\"",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      },
      {
        "id":17,
        "gender":"female",
        "title":"Ms.",
        "firstName":"Violet",
        "middleInitial":"R",
        "surname":"McDowell",
        "streetAddress":"1301 Fannie Street",
        "city":"San Angelo",
        "state":"TX",
        "zipCode":"76903",
        "country":"United States",
        "email":"VioletRMcDowell@cuvox.de",
        "username":"Repask",
        "birthday":"12/18/1942",
        "occupation":"Clerical specialist",
        "company":"Briazz",
        "latitude":"31.499164",
        "longitude":"-100.376579",
        "motto":"WHO CARES where Carmen Sandiego is?",
        "portrait":"http://s1.postimg.org/j5mytq3iz/profile.jpg"
      }
      ];
  }
})();
